swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Swagger tasks"
host: "localhost:4000"
basePath: "/v1"
tags:
- name: "tareas"
  description: "operaciones sobre tareas"
schemes:
- "http"
paths:
  /task:
    post:
      tags:
      - "tareas"
      summary: "Add a new task"
      description: "add new task"
      operationId: "addtask"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/task"
      responses:
        "405":
          description: "Invalid input"
    get:
      tags:
      - "tareas"
      summary: "return json of task"
      description: "return json of task"
      operationId: "findtasksByStatus"
      produces:
      - "application/json"
      
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/task"
        "400":
          description: "Invalid status value"
  /task/{id}:
    get:
      tags:
      - "tareas"
      summary: "return task for id"
      description: "return task for id"
      operationId: "gettaskById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ingresar el id de la tarea que desea ver"
        required: true
        type: "integer"
      
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/task"
        "400":
          description: "Invalid status value"
    put:
      tags:
      - "tareas"
      summary: "edit one task"
      description: "permite editar tareas guardadas"
      operationId: "updatetask"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "titulo"
        in: "path"
        description: "titulo de la tarea"
        required: true
        type: "string"
      - name: "descripcion"
        in: "path"
        description: "descripcion de la tarea"
        required: true
        type: "string"
      - name: "nombre_usuario"
        in: "path"
        description: "creador de la tarea"
        required: true
        type: "string"
      - name: "estado"
        in: "path"
        description: "numero de estado de la tarea"
        required: true
        type: "integer"
  
      responses:
        "405":
          description: "Invalid input"
    delete:
      tags:
      - "tareas"
      summary: "delete task"
      description: "permite eliminar tareas guardadas"
      operationId: "deletetask"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "task id to delete"
        required: true
        type: "integer"
      responses:
        "200":
          description: "mensage: task deel!!"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "task not found"
definitions:
  task:
    type: "object"
    properties:
      title:
        type: "string"
        example: "correr"
      description:
        type: "string"
        example: 'tengo que salir a correr'
      nombre_usuario:
        type: "string"
        example: "maria"
      estado:
        type: "integer"
        description: "1 = tarea asignada, 2 = tarea en proceso, 3 = bloqueado, 4 = tarea terminada"
        enum:
        - 1
        - 2
        - 3
        - 4
    xml:
      name: "task"
